package me.getrundelthd.main.engine.items

enum class ITEMS { WOODEN_SWORD, WHITE_SWORD, MAGICAL_SWORD, BLUE_RING, RED_RING,
              SMALL_SHIELD, MAGICAL_SHIELD, BOOMERANG, MAGICAL_BOOMERANG,
              BONG, BOOK_OF_MAGIC, MAGICAL_ROD, ARROW, BOW,
              SILVER_ARROW, RAFT, STEPLADDER, HEART_CONTAINER, BLUE_CANDLE,
              RED_CANDLE, RECORDER, POWER_BRACELET, MAGICAL_KEY, FOOD,
              LIFE_POTION, SECOND_POTION }

enum class COLLECTALBLES {
    HEARTH, RUBY, ARROW
}